# Generated by Django 2.1.8 on 2019-05-24 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('birth', models.DateField(default=django.utils.timezone.now)),
                ('nationality', models.CharField(choices=[('한국', 'KR'), ('일본', 'JP'), ('대만', 'TW')], max_length=20)),
                ('position', models.TextField(max_length=20)),
            ],
        ),
    ]
